name: Update Icon Gallery

on:
  schedule:
  - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:      # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0   # fetch full history for branch switching

    - name: Make script executable
      run: chmod +x ./generate-gallery.sh

    - name: Generate icon gallery
      run: |
        ./generate-gallery.sh --columns 4 --output /tmp/index.html

    - name: Deploy to gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Configure git identity
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # Fetch and checkout gh-pages branch
        git fetch origin gh-pages
        git checkout gh-pages

        # Copy the new index.html
        cp /tmp/index.html ./index.html

        # Check if index.html actually changed
        if git diff --quiet index.html; then
          echo "No changes in index.html. Skipping commit."
          exit 0
        fi

        # Add files and commit
        git add index.html
        DATE=$(date -u +"%Y-%m-%d")
        git commit -m "Update icon gallery - $DATE [skip ci]"

        # Push to gh-pages
        git push origin gh-pages

